- name: Stage xml update script into ~/.kodi
  copy:
    src: update_xml.py
    dest: "~{{ kodi_user }}/.kodi"
    owner: "{{ kodi_user }}"
    mode: "0700"
  tags: configure

- name: Update XML
  command:
    cmd: "~{{ kodi_user }}/.kodi/update_xml.py {{ item.file | quote }} {{ item.key | quote }} {{ item.value | quote }} {{ item.type | quote }}"
  with_items: "{{ kodi_config }}"
