- name: Stage xml update script into ~/.kodi
  copy:
    src: update_xml.py
    dest: "~{{ kodi_user }}/.kodi"
    owner: "{{ kodi_user }}"
    mode: "0700"
  tags: configure

- name: Update XML
  command:
    cmd: '~{{ kodi_user }}/.kodi/update_xml.py ''{{ item.file }}'' ''{{ item.key }}'' ''{{ item.value }}'' ''{{ item.type }}'' '
  with_items: "{{ kodi_config }}"
  tags: configure
