- name: Update XML
  script:
    cmd: "update_xml.py {{ item.file | quote }} {{ item.key | quote }} {{ item.value | quote }} {{ item.type | quote }}"
  with_items: "{{ kodi_config_final }}"
  tags: configure
